### PR TITLE
Add pod ready check on new nodes

### PR DESCRIPTION
**Pull request by bobmacks**
Add a condition to check for pods to be in ready state before draining the next nodes

### CODE REVIEW

**Comment by aarongorka** [comment]
The reason I didn't add this is that in a sufficiently large enough cluster/organisation, the chances of every single pod in the cluster being ready at the same time is pretty unlikely (especially as you start looking at lower environments that have e.g. development deployments). I think that if we did need this feature, it would have to be opt-in via a flag or something, and you'd have to check the state of the cluster to make sure all pods are ready before even starting the upgrades.

Have you seen service degradation as a result of this feature being missing?

**Comment by bobmacks** [comment]
@aarongorka, we have a fairly small setup at the moment - 3 node cluster and 2 replicas. 
Our app pods that can take up to 2-4 minutes to start until they're ready. As a result we're running into a scenario where eks-node-rollout starts draining the next nodes while recently evicted pods are still starting on the other nodes. Midway through the node rollout we'll most likely see a 30sec to 1min outage.

**Comment by aarongorka** [comment]
@bobmacks sorry for the late reply, this slipped my mind
> Our app pods that can take up to 2-4 minutes to start until they're ready. As a result we're running into a scenario where eks-node-rollout starts draining the next nodes while recently evicted pods are still starting on the other nodes. Midway through the node rollout we'll most likely see a 30sec to 1min outage.

Kubernetes won't finalise the draining process until a new pod has been successfully launched, so this won't happen even without waiting for all the pods to be ready - as long as you've configured a PodDisruptionBudget that indicates that there should always be n pods running at all times. 

https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets
https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#the-eviction-api

**Comment by bobmacks** [comment]
Thanks for the hint. I’ll look into PodDisruptionBudget and see if this works for us.

**Comment by bobmacks** [comment]
Apologies for the late update. Was able to utilise PDBs to guarantee a minimum of 1 pod running at all times

**Pull request closed without merging**
